# Generated by Django 4.0.4 on 2022-05-12 09:53

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_remove_job_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
