# Generated by Django 4.0.4 on 2022-05-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='point',
            new_name='points',
        ),
    ]
