# Generated by Django 4.0.4 on 2022-05-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_point_job_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='points',
        ),
    ]
